### PR TITLE
Add AnUitor link

### PR DESCRIPTION
**Pull request by jbruchanov**

### CODE REVIEW

**Comment by aritraroy** [comment]
Thank you for your contribution. But you need to add it maintaining the default sort order of the category i.e. alphabetical sort order. Please make the required changes and let me know.

**Comment by jbruchanov** [comment]
@aritraroy done...

**Comment by aritraroy** [comment]
I have tried it. It doesn't seem to be mature enough. We are only adding mature and well-tested resources here. Please re-raise a PR later when the library gets more mature and tested.

**Comment by jbruchanov** [comment]
@aritraroy can you be more specific ?

**Comment by aritraroy** [comment]
I am only including tools and libraries which have been battle-tested by several developers for a long time. Your tool is good, but it needs to be tried, tested and used by a lot of developers to make it to this list. Hope you will understand.

**Pull request closed without merging**
