### PR TITLE
Added 4 new links

### PR DESCRIPTION
**Pull request by bapspatil**
This new link would be really helpful for developers looking for an API for a specific purpose.

### CODE REVIEW

**Comment by bapspatil** [comment]
These links might be really helpful

**Comment by bapspatil** [comment]
Talking Kotlin is a great Podcast for people who are new to Kotlin.
AndroidPub has a great newsletter that every Android developer should subscribe to.

**Comment by bapspatil** [comment]
Done.

**Comment by aritraroy** [comment]
Your PR is approved. But there are some merge conflicts. Can you take the latest pull, fix the conflicts and push again?

**Comment by bapspatil** [comment]
Done.

**Pull request merged**
