### PR TITLE
Add Splitties

### PR DESCRIPTION
**Pull request by LouisCAD**
Added an Android Library named Splitties: https://github.com/LouisCAD/Splitties

### CODE REVIEW

**Comment by aritraroy** [comment]
This library is good but doesn't make the cut to be included in this list. Closing. :-)

**Comment by LouisCAD** [comment]
@aritraroy What is wrong with it that "doesn't make the cut"?

**Comment by aritraroy** [comment]
There is absolutely nothing wrong with it. Currently, I am not inclined towards including it in this list. You can always raise a PR in the future. Hope you will understand. Thanks.

**Comment by LouisCAD** [comment]
And could you tell me why you're not inclined to include it? What are the
criterias on which you decide to include a library or not in the list?

Le mer. 3 mai 2017 à 3:28 PM, Aritra Roy <notifications@github.com> a
écrit :

**Comment by aritraroy** [comment]
There are several things I try to look at, some of them being how popular the library is, how many developers was it able to reach, how long the library is being developed consistently and how well-tested it is.

**Pull request closed without merging**
